---
- name: customize osx default
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    # Finder (Need: "killall Finder")
    # Show Status bar in Finder
    - { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
    # Show Path bar in Finder
    - { domain: com.apple.finder, key: ShowPathbar, type: bool, value: true }
    # Show Tab bar in Finder 
    - { domain: com.apple.finder, key: ShowTabView, type: bool, value: true }
    # Show hidden file
    - { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }
    # Show list format
    - { domain: com.apple.finder, key: FXPreferredViewStyle, type: string, value: "Nlsv" }
    # # Show the ~/Library directory （ライブラリディレクトリを表示、デフォルトは非表示）
    # chflags nohidden ~/Library
    # 拡張子表示
    - { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: true }
    # hide dock (Need "killall Dock")
    - { domain: com.apple.dock, key: autohide, type: bool, value: true }
    # show battery percent(Need "killall SystemUIServer")
    - { domain: com.apple.menuextra.battery, key: ShowPercent, type: string, value: "YES" }
    # show date setting
    - { domain: com.apple.menuextra.clock, key: DateFormat, type: string, value: "EEE H:mm:ss" }
    # set screensaver
    - { domain: /Library/Preferences/com.apple.screensaver, key: loginWindowIdleTime, type: int, value: 300 }
    # スリープまたはスクリーンセーバから復帰した際、パスワードをすぐに要求する
    - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
    - { domain: com.apple.screensaver, key: askForPasswordDelay, type: int, value: 0 }
    # firewall
    - { domain: /Library/Preferences/com.apple.alf, key: globalstate, type: int, value: 1 }
    # 以下は defaults では設定不可らしい
    # FileVault2
    # auto update setting

- name: install base tools with brew
  homebrew:
    name:
      - bash-completion
      - tmux
      - zsh
      - peco
      - go-task/tap/go-task
      - vim
      - direnv
      - pwgen
      - gawk
      - gnu-sed
      - jq
      - tig
    state: present
    update_homebrew: yes

- name: install base tools with brew cask
  homebrew_cask:
    name: "{{ item }}"
    state: present
    update_homebrew: yes
  with_items:
    - slack
    - clipy
    - google-japanese-ime
    - google-chrome
    - karabiner-elements
