---
- name: install dev tools with cask
  homebrew_cask:
    name: "{{ item}}"
    state: present
    update_homebrew: yes
  with_items:
    - docker
    - font-inconsolata-for-powerline
    - iterm2
    - visual-studio-code
